import {
  app,
  BrowserWindow,
  desktopCapturer,
  ipcMain,
  powerMonitor,
} from "electron";
import { GlobalKeyboardListener } from "node-global-key-listener";
const v = new GlobalKeyboardListener();
v.addListener(function (e, down) {
  console.log(
    `${e.name} ${e.state == "DOWN" ? "DOWN" : "UP  "} [${e.rawKey._nameRaw}]`
  );
});
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
import ActiveWindow from "@paymoapp/active-window";

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

// declare active time variables
let activeTime = 0;
let monitoringStarted = false;
let interval: number | NodeJS.Timeout;
let lockInterval: number | NodeJS.Timeout;

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1000,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();

  // taking screenshot
  ipcMain.on("take-screenshot", () => {
    desktopCapturer
      .getSources({
        types: ["screen"],
        thumbnailSize: { width: 300, height: 200 },
      })
      .then((sources) => {
        const dataURL = sources[0].thumbnail.toDataURL();
        ActiveWindow.initialize();

        if (!ActiveWindow.requestPermissions()) {
          console.log(
            "Error: You need to grant screen recording permission in System Preferences > Security & Privacy > Privacy > Screen Recording"
          );
          process.exit(0);
        }

        const activeWin = ActiveWindow.getActiveWindow();
        mainWindow.webContents.send("screenshot-data", {
          dataURL: dataURL,
          activeWin: activeWin.title,
        });
      });
  });

  ipcMain.on("request-active-time", (event) => {
    event.sender.send("active-time", activeTime);
  }); // Variable to track the time of the last system resume event

  ipcMain.on("start-monitoring", () => {
    if (!monitoringStarted) {
      interval = setInterval(() => {
        activeTime++;

        mainWindow.webContents.send("active-time", activeTime);
      }, 1000);
      monitoringStarted = true;
    }
  });
  powerMonitor.on("suspend", () => {
    if (monitoringStarted) {
      if (interval) clearInterval(interval);
      if (lockInterval) {
        clearInterval(lockInterval);
      } // Correct way to clear the interval
    }
  });
  powerMonitor.on("lock-screen", () => {
    if (monitoringStarted) {
      if (interval) clearInterval(interval);
      // Correct way to clear the interval
      if (lockInterval) {
        clearInterval(lockInterval);
      }
    }
  });

  powerMonitor.on("unlock-screen", () => {
    if (monitoringStarted) {
      lockInterval = setInterval(() => {
        activeTime++;
        mainWindow.webContents.send("active-time", activeTime);
      }, 1000);
    }
  });
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
